package org.gwt.dmesg.client;

/**
 * Message bundle loader implementation.
 * 
 * <p>
 * SPI class, provides a backend for {@link Messages} with deferred binding.
 * </p>
 * 
 * @author Gergely Kiss
 * 
 * @see org.gwt.dmesg.client.Messages
 * @see org.gwt.dmesg.rebind.DynamicMessagesGenerator
 * 
 * @since 1.0
 */
class MessageBundleImpl {

	// Real loading implementation is generated by deferred binding
	public native void load()
	/*-{
		$wnd['messages'] = {};
	}-*/;
}
